MVC_MusicStore/Controllers/ShoppingCartController.cs
using MVC_MusicStore.Models;
using MVC_MusicStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_MusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        MusicStoreContext storeDB = new MusicStoreContext();
        //         
        // GET: /ShoppingCart/  
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Set up our ViewModel             
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view            
            return View(viewModel);
        }

        //         // GET: /Store/AddToCart/5  
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database             
            var addedAlbum = storeDB.AlbumsSet
                .Single(album => album.AlbumId == id);
            // Add it to the shopping cart             
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedAlbum);
            // Go back to the main store page for more shopping             
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart             
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Get the name of the album to display confirmation             
            string albumName = storeDB.Carts                 
                .Single(item => item.RecordId == id).Album.Title;
            // Remove from cart             
            int itemCount = cart.RemoveFromCart(id);
            // Display the confirmation message             
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) + " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };  
            return Json(results);
        }

        //        
        // GET: /ShoppingCart/CartSummary  
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}   
        

MVC_MusicStore/Controllers/StoreController.cs
using MVC_MusicStore.Generic;
using MVC_MusicStore.Models;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace MVC_MusicStore.Controllers
{
    [Authorize]
    [NotifyException]
    public class StoreController : Controller
    {
        MusicStoreContext db = new MusicStoreContext();

        // GET: Store 
        public ActionResult Index()
        {
            var albums = db.AlbumsSet.Include(a => a.Genre).Include(a => a.Artist);
            return View(albums.OrderByDescending(p => p.AlbumId).Take(18));
        } 

        // GET: Browse Album by Genre
        public ActionResult Browse(string Genre)
        { 
            var albums = db.AlbumsSet.Include(a => a.Genre).Include(a => a.Artist);
            var albumslist = albums.Where(a => a.Genre.Name == Genre).Take(14);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_AlbumList", albumslist);
            }
            else
            {
                return View(albumslist);
            }
            
        } 
        
        // Get: /StoreManager/Details/id        
        public ActionResult Details(int id)
        {
            Album album = db.AlbumsSet.Find(id);
            Genre genre = db.GenresSet.Find(album.GenreId);
            ViewBag.GenereName = genre.Name;
            Artist artist = db.ArtistsSet.Find(album.ArtistId);
            ViewBag.ArtistName = artist.Name;
            return View(album);
        }

        [ChildActionOnly] 
        public ActionResult _GenreMenu()
        {
            var genres = db.GenresSet.ToList();

            return PartialView(genres);
        }
    }
}

MVC_MusicStore/Views/Store/Browse.cshtml
@model IEnumerable<MVC_MusicStore.Models.Album>

@{
    ViewBag.Title = "Browse";
}

<h2>Browse</h2>
<ul id="album-list">
    @foreach (var album in Model)
    {
        <li>
            <a href="@Url.Action("Details", "Store",
                new { id = album.AlbumId })">

                <img alt="@album.Title" src="~/@album.AlbumArtUrl" />
                <span>@album.Title</span>
            </a>
        </li>
    }
</ul>

MVC_MusicStore/Views/Store/Details.cshtml
@model MVC_MusicStore.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>@Model.Title</h2>
<p> <img alt="@Model.Title" src="@Model.AlbumArtUrl" /> </p>
<div id="album-details">
    <p>
        <em>Genre:</em>
        @Model.Genre.Name
    </p>
    <p>
        <em>Artist:</em>
        @Model.Artist.Name
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}", Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { id = Model.AlbumId }, "")
    </p>
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

MVC_MusicStore/Views/Store/Index.cshtml
@model IEnumerable<MVC_MusicStore.Models.Album>

@{
    ViewBag.Title = "Index";
}

<h2>Album Store</h2>

<ul id="album-list">
    @foreach (var album in Model)
    {
        <li>
            <a href="@Url.Action("Details", "Store",
                new { id = album.AlbumId })">

                <img alt="@album.Title" src="~/@album.AlbumArtUrl" />
                <span>@album.Title</span>
                <p class="button">         
                @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { id = album.AlbumId }, "")     
                </p>
                
            </a>
        </li>
    }
</ul>

MVC_MusicStore/Views/Store/_AlbumList.cshtml
@model IEnumerable<MVC_MusicStore.Models.Album>
<hr />
<ul id="album-list">
    @foreach (var album in Model)
    {
        <li>
            <a href="@Url.Action("Details", "Store",
                new { id = album.AlbumId })">

                <img alt="@album.Title" src="~/@album.AlbumArtUrl" />
                <span>@album.Title</span>
            </a>
        </li>
    }
</ul>

MVC_MusicStore/Views/Store/_GenreMenu.cshtml
@model IEnumerable<MVC_MusicStore.Models.Genre>

<ul id="categories">
    @foreach (var genre in Model)
    {
        <li> 
            <a href="" data-id="@genre.Name" class="genreName">@genre.Name</a>
        </li>
    }
</ul>